import Footer from './Footer'
import Header from './Header'
import Main from './Main'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nextjs-TS-TailwindCSS Template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className="min-h-screen flex flex-col">
      <Header />
        <Main>
          {children}
        </Main>
      <Footer />
      </body>
    </html>
  )
}
